apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: notification-service
spec:
  sink:
    properties:
      channel: '#ocp-demo'
      webhookUrl: https://hooks.slack.com/services/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
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: slack-sink
  source:
    properties:
      type: singaporean
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: record-processed