apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: record-received
spec: {}

---

apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: record-to-be-processed
spec: {}

---

apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: record-processed
spec: {}